export const UPDATE_ITEM = "UPDATE_ITEM";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREMENT_CART_ITEM_COUNT = "INCREMENT_CART_ITEM_COUNT";
export const DECREMENT_CART_ITEM_COUNT = "DECREMENT_CART_ITEM_COUNT";